
version: "3.9"

services:
  backend:
    build: ./backend
    container_name: chatlog-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    image: python:3.12
    container_name: chatlog-frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "8501:8501"
    command: ["sh", "-c", "pip install -r requirements.txt && streamlit run app.py --server.port=8501 --server.address=0.0.0.0"]
