STOP_WORDS = set([
    'a', 'an', 'and', 'are', 'as', 'at', 'be', 'by', 'for', 'from',
    'has', 'he', 'in', 'is', 'it', 'its', 'of', 'on', 'that', 'the',
    'to', 'was', 'will', 'with', 'i', 'you', 'me', 'my', 'we', 'our',
    'your', 'yours', 'they', 'them', 'their', 'theirs', 'this', 'that',
    'these', 'those', 'what', 'which', 'who', 'when', 'where', 'why',
    'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other',
    'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so',
    'than', 'too', 'very', 's', 't', 'can', 'could', 'should', 'would',
    'may', 'might', 'must', 'shall', 'do', 'does', 'did', 'have', 'had',
    'having', 'am', 'is', 'are', 'was', 'were', 'been', 'being', 'get',
    'got', 'go', 'goes', 'going', 'went', 'gone', 'make', 'made', 'making',
    'take', 'took', 'taken', 'taking', 'come', 'came', 'coming', 'say',
    'said', 'saying', 'see', 'saw', 'seen', 'seeing', 'know', 'knew',
    'known', 'knowing', 'think', 'thought', 'thinking', 'work', 'worked',
    'working', 'use', 'used', 'using', 'want', 'wanted', 'wanting', 'like',
    'liked', 'liking', 'time', 'times', 'way', 'ways', 'day', 'days',
    'year', 'years', 'person', 'people', 'thing', 'things', 'place',
    'places', 'good', 'great', 'better', 'best', 'bad', 'worse', 'worst',
    'big', 'bigger', 'biggest', 'small', 'smaller', 'smallest', 'long',
    'longer', 'longest', 'short', 'shorter', 'shortest', 'high', 'higher',
    'highest', 'low', 'lower', 'lowest', 'new', 'newer', 'newest', 'old',
    'older', 'oldest', 'first', 'last', 'next', 'previous', 'one', 'two',
    'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten'
])